# Generated by Django 3.2.4 on 2021-06-21 06:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'not active'), (1, 'active'), (2, 'accepted')], default='active')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 12, 0))),
                ('receiver_subs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='SubApp.subscribers')),
                ('sender_subs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='SubApp.subscribers')),
            ],
        ),
    ]
