# Generated by Django 3.2.4 on 2021-06-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invites',
            name='receiver_subs',
        ),
        migrations.AddField(
            model_name='invites',
            name='recipient_subs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='SubApp.subscribers'),
            preserve_default=False,
        ),
    ]
